var artists = {
  nameList: [
    "Franz Ackermann",
    "Etel Adnan",
    "Darren Almond",
    "Ellen Altfest",
    "Michael Armitage",
    "Miroslaw Balka",
    "Georg Baselitz",
    "Larry Bell",
    "Jake & Dinos Chapman",
    "Chuck Close",
    "Gregory Crewdson",
    "Tracey Emin",
    "Katharina",
    "Fritsch Theaster",
    "Gates Gilbert & George",
    "Antony Gormley",
    "Andreas Gursky",
    "David Hammons",
    "Mona Hatoum",
    "He Xiangyu ",
    "Damien Hirst ",
    "Robert Irwin",
    "Runa Islam ",
    "Sergej Jensen ",
    "Anselm Kiefer ",
    "Rachel Kneebone ",
    "Imi Knoebel",
    "Elad Lassry",
    "Liza Lou",
    "Jac Leirner",
    "Liu Wei",
    "Christian Marclay ",
    "Josiah McElheny ",
    "Julie Mehretu",
    "Beatriz Milhazes",
    "Harland Miller",
    "Sarah Morris",
    "Gabriel Orozco",
    "Damián Ortega",
    "Virginia Overton",
    "Eddie Peake",
    "Magnus Plessen",
    "Jessica Rankin",
    "Christian Rosa",
    "Doris Salcedo",
    "Raqib Shaw",
    "Haim Steinbach",
    "Sam Taylor-Johnson",
    "Fred Tomaselli",
    "Jeff Wall",
    "Cerith Wyn Evans"
  ].sort()
};
